### ISSUE TITLE
Play around with getting code deployed on AWS

### ISSUE THREAD

**Issue by cruoti** [discapp/discapp#1]
I think everyone needs to get familiar with AWS.  Melissa made a really good diagram showing the different components of AWS that we'll need.  I think we all need to do tutorials for those components and get familiar.  My goal is to have explored all of these items by our meeting on Monday so I have a good feel for what needs to be done in the project.  

At the meeting, I want us to use our collective knowledge of AWS to come up with a very good to-do list with specific deadlines of the items that we need to accomplish for our first deliverable.

**Comment by cruoti** [comment]
From @mrossi113 

![aws blueprint](https://user-images.githubusercontent.com/25518813/26998980-96d5232e-4d5c-11e7-9b4b-cc55395ef924.png)

**Comment by cruoti** [comment]
Here are some AWS 10 minute tutorials that may be helpful (all 10 min. tutorials at https://aws.amazon.com/getting-started/tutorials/):

**Run a Serverless "Hello, World"**
https://aws.amazon.com/getting-started/tutorials/run-serverless-code/

**Launch a Web Application**
https://aws.amazon.com/getting-started/tutorials/launch-an-app/

**Update a Web Application**
https://aws.amazon.com/getting-started/tutorials/update-an-app/

**Create and Query a NoSQL DB**
https://aws.amazon.com/getting-started/tutorials/create-nosql-table/

**Deploy Code To A Virtual Machine**
https://aws.amazon.com/getting-started/tutorials/deploy-code-vm/

**Comment by mrossi113** [comment]
**Create and Connect to a MySQL Database (with Amazon RDS)**
https://aws.amazon.com/getting-started/tutorials/create-mysql-db/

**I would recommend the YouTube video and documentation about AWS CodePipeline** https://aws.amazon.com/codepipeline/?nc2=h_l3_dm
