### ISSUE TITLE
Local project build

### ISSUE THREAD

**Issue by cruoti** [discapp/discapp#10]
@mrossi113 

How do you have your project setup locally?  I can get the `.html` files to load in my browser if I drag them over.  However, I'm not getting a dynamic web project in Eclipse to run with them.  I think I'm missing something simple.  

If nothing else, you could push a new branch that does not have the `.gitignore` file so that I could see the whole setup.

**Comment by mrossi113** [comment]
@cruoti I was using Intellij for the HTML pages for so much easier to run compared to Eclipse. We are missing a web.xml for this project.

**Comment by cruoti** [comment]
I see.  I actually had moved over to IntelliJ as well.  You'll see that I put together some more things in my pull request (#11).
