### ISSUE TITLE
AWS Charges

### ISSUE THREAD

**Issue by cruoti** [discapp/discapp#18]
@mrossi113 @todoubled711 @ktaj

I just received a billing statement from Amazon for my June usage.  It looks like all the charges are related to Elastic Beanstalk.  Has anyone else been charged for their use of Beanstalk or anything else?  I thought I was doing things on the Free Tier, but I guess Beanstalk wasn't covered like I thought it was.

**Comment by mrossi113** [comment]
@cruoti I don't have a bill for elastic beanstalk for month June. What are you running on elastic beanstalk?

Below is from Elastic Beanstalk pricing https://aws.amazon.com/elasticbeanstalk/pricing/:
"New AWS customers who are eligible for the AWS free usage tier can deploy an application in Elastic Beanstalk for free, as the default settings for Elastic Beanstalk allow a low traffic application to run within the free tier without incurring charges. If these applications require more resources than the default environment provides, customers will be charged the normal AWS rates for the incremental resources the application consumes"

**Comment by cruoti** [comment]
I looked into the bill some more. It looks like I had some hours with a free tier t2.micro server but then I also had a lot of hours on an on-demand t2.micro server.  I'm not sure how I set that up.  I'll just have to be careful next time and look at all the options.
