### ISSUE TITLE
Help With Cloud Watch

### ISSUE THREAD

**Issue by cruoti** [discapp/discapp#23]
Here is the email we all received from @todoubled711.  I think the GitHub issue is a better place for it than our email.  A lot of the motivation is so that Prof. Davidow can see it since he has access to our GitHub page.

> Hi Team,
> 
> I am having troubles setting up the logs for ElasticBeanStalk and RDS. I have went through this guide https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/QuickStartEC2Instance.html and completed the first portion for setting up the inline policy for the elasticbeanstalk and rds roles.
> 
>
> 
> ![image](https://user-images.githubusercontent.com/25518813/28043615-adb98d8a-65a0-11e7-82ad-0b97b49582cb.png)
> 
> ![image 1](https://user-images.githubusercontent.com/25518813/28043626-b8a7e87c-65a0-11e7-829d-5713f7e71013.png)
> 
> ![image 2](https://user-images.githubusercontent.com/25518813/28043633-c0c9d9a2-65a0-11e7-9dbf-b794e079394a.png)
> 
> for the second portion of the document I need to connect to the instances then install and configure the CloudWatch logs. This is the portion I am having trouble with as I am not able to connect to the Instances.
> 
> I followed this video: https://www.youtube.com/watch?v=bi7ow5NGC-U and created a new key pair set then got putty and putty generator. Then generated a new key using the keypair set. This way it can be recognized by putty. I did all off that and am unable to access the instance I get a time out error.
> 
> Also, when I try to connect to the elastic beansstalk instance to get the username and hostname I get these warnings:
> 
> ![image 3](https://user-images.githubusercontent.com/25518813/28043644-d640f13a-65a0-11e7-856f-d12f559b7092.png)
> 
> 
> One more thing, I will be available early in the day tomorrow but will be unavailable afternoon. I forgot to mention last week (had my weeks confused and thought it was two weeks away) that my mom and I have to attend a court hearing (No we aren't in trouble). It is also my birthday so my wife and mom want to take me out after the hearing.
> 
> Please let me know if there is anything else I can help with
> 
> Regards,
> 
> https://www.youtube.com/watch?v=bi7ow5NGC-U&authuser=0
> 
> I forgot to mentioned that I did create the Log groups and Log streams as well. Just nothing is coming back at the moment because it isn't fully setup.

**Comment by todoubled711** [comment]
Thanks @cruoti!

**Comment by todoubled711** [comment]
Once we can access the instance it doesn't look very hard to setup.

**Comment by cruoti** [comment]
@todoubled711 

I just read through the full email.  I'm not really sure on the solution.  I've not tried anything with Cloud Watch up to this point so, ..., I'm not sure.  

@mrossi113 

Do you have any ideas about port 22 on instances and what might be preventing Todd from getting in?  I've no clue.  I'll focus on other things till our meeting and then we'll reassess where each of our time needs to be focused.

**Comment by mrossi113** [comment]
@cruoti we figure out the port 22 instance. If any other troubles with CloudWatch @todoubled711 let me know. @todoubled711 if not just close this issue once CloudWatch Logs are working.

**Comment by todoubled711** [comment]
This issue has been resolved.
