### ISSUE TITLE
Issue with CodePipeline

### ISSUE THREAD

**Issue by mrossi113** [discapp/discapp#3]
For some reason I have no access to this repo when I try to setup the CodePipeline. It says I need `You must have, at minimum, read-only access to the repository.` I'm not sure with Collaborator gives you that access. 

Could you setup the CodePipeline or give me access to the repo?

**Comment by mrossi113** [comment]
![screen shot 2017-06-12 at 9 38 32 pm](https://user-images.githubusercontent.com/19477691/27062218-89651fac-4fb7-11e7-992d-5aa1611566a8.jpg)
![screen shot 2017-06-12 at 9 38 06 pm](https://user-images.githubusercontent.com/19477691/27062223-938df008-4fb7-11e7-819c-b4190b696275.jpg)

**Comment by cruoti** [comment]
I will look into getting you access.  If I can't figure it out in the next 20 minutes or so, then I'll create the pipeline.

**Comment by cruoti** [comment]
@mrossi113,

I started making the pipeline.  I didn't know if I should select the Tomcat or the Java platform for elastic beanstalk so I stopped.  You can let me know which one I should select.

Also, I moved the repo into the 'discapp' organization where you should have more fine grained control of the repo.  The settings now say that you have *write* access.  I suggest you try making the pipeline and seeing if you now have access to it.  If not, tell me to select either Tomcat or Java platform and I'll finish making the pipeline.

**Comment by cruoti** [comment]
@mrossi113 

I just saw your note on LATTE that you need Admin rights.  I went ahead and switched that in the settings.  The whole team has admin rights now.

**Comment by mrossi113** [comment]
@cruoti I have access to the repo for CodePipeline now. I will setup the CodePipeline. I've used Tomcat version 8 in the past for Elastic Beanstalk and Eclipse IDE. Do you have preference for Java application? 

Also I sent @keeena a slack message to see if he was working on creating the Elastic Beanstalk instance before I start making a new one.

**Comment by cruoti** [comment]
@mrossi113 
Tomcat works for me.  When I took the web development class it is the server we used.  It's been awhile, so it'll be good to brush off the dust since that class.

**Comment by mrossi113** [comment]
@cruoti You might be getting an email from AWS to grant me access. I was able to add the GItHub repo, but It asked to grant access from the owner of the repo.

**Comment by cruoti** [comment]
@mrossi113 
I granted access.  I'm calling it done for the night.  I'll check in before work in the morning to see if there is anything anyone needs.

**Comment by mrossi113** [comment]
@cruoti The CodePipeline has been created and succeed on it first pass from GitHub repo to Elastic Beanstalk. I have the CodePipeline tracking the master branch at the moment. Do you want to switch it develop branch? So that we can test the web application each time we merge a pull request into the develop branch.

**Comment by cruoti** [comment]
Ultimately, I think it should be the master branch.  However, it might be good for it to be the develop branch at the moment.

**Comment by mrossi113** [comment]
@cruoti Yeah I was thinking the same thing. If we need to either of us can change CodePipeline at any point. I going to change make the default branch be `develop` for now.
