### ISSUE TITLE
UI Sketches

### ISSUE THREAD

**Issue by cruoti** [discapp/discapp#4]
My scanner broke so I just took pictures with my phone.  I'll scan the page at work tomorrow and send a cleaner copy then.  I split the UI into three main screens for now:

1. login screen (either using google credentials or having to design our own)
2. user dashboard
  - select to add new scores
  - review recent scores from all courses
  - select course to review full history
    - show full history with that course and a chart to quickly visualize scores over time
3.  add new score screen
  - use dropdown to select which course
  - add date
  - show par for course
  - input data
  - submit scores or cancel

If we can get all these features implemented, then we could start on adding the other ones in.

![login_screens](https://user-images.githubusercontent.com/25518813/27113453-dd0b7344-508a-11e7-892d-71137a0bfda6.jpg)

![user_dashboard](https://user-images.githubusercontent.com/25518813/27113462-ee1196fa-508a-11e7-833f-c1b3728b842c.jpg)

![add_new_score](https://user-images.githubusercontent.com/25518813/27113464-f77860a2-508a-11e7-9a5e-03d98a4de4d0.jpg)

**Comment by todoubled711** [comment]
Chris,
I know we are working on designing these in HTML. Do you have a preference on which screen you want to work on? I just want to make sure we aren't building out the same screens.

Thanks,
Todd

**Comment by cruoti** [comment]
I don't actually care too much which screen I work on.  I'm going to try to design out some of the code for the backend of the UI.  So if you want to focus on the HTML that works for me.  Once I'm done with that, I can see where you are at with things.

**Comment by todoubled711** [comment]
Awesome sounds like fun! I am trying to read your comment for the first image. Does it say we don't have to worry about designing a login screen if we are able to tap into Google login? I know Melissa left a comment and might have a solution for the google login.

**Comment by cruoti** [comment]
Yeah, the comment says that I don't think we need to design the login screen if we tap into google.  @mrossi113 is looking into it so she'll probably know for sure.

**Comment by mrossi113** [comment]
@cruoti @todoubled711 I've built the Google login on the index.html page within the `login-screen` branch I still need to work on it. But I've created a pull request, but still a work in progress and I need to create the homepage once someone login to app. Within that branch. I've created script.js and style.css files just in case to create the index page. If you guys want to use that branch go ahead for design either to test by add color, logo, and etc. whatever you want. Change any of the CSS I've added if needed.

Also the login screen needs some text before the login button not sure if anyone had something in mind for it.

![screen shot 2017-06-15 at 12 57 08 am](https://user-images.githubusercontent.com/19477691/27166032-ec77bb90-5165-11e7-951e-72e25a99286f.jpg)

**Comment by ktaj** [comment]
@cruoti - I took a look at the screenshots and i believe the data model will fully support everything you have shown. The only little item I'm aware of (both the DB model and your UI have the issue) is that the Games are unique by Date Played (which I believe is a Date datatype). The data will become junk once you insert 2 games on the same day. I'd like to add a Game Number or Name to make it a bit more usable/precise.

Also, can you please send a new invite to this Github account? I'd rather use my Brandeis account than my personal one.

**Comment by cruoti** [comment]
@keeena, do you have a username associated with your Brandeis email?  I'll need to know that account username in order to add you as a collaborator.

**Comment by ktaj** [comment]
My GitHub associated with my Brandeis email is @ktaj

On Jun 15, 2017 10:01 PM, "cruoti" <notifications@github.com> wrote:

@keeena <https://github.com/keeena>, do you have a username associated with
your Brandeis email? I'll need to know that account username in order to
add you as a collaborator.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/discapp/discapp/issues/4#issuecomment-308912517>, or mute
the thread

**Comment by todoubled711** [comment]
I have a rough copy of the screens built out in HTML. I am not familiar with GitHub so tomorrow I will spend some time trying to understand how to upload my code to here.
