### ISSUE TITLE
I don't see anything in AWS IAM Account

### ISSUE THREAD

**Issue by cruoti** [discapp/discapp#7]
@mrossi113 

When I log into the IAM account I don't see anything under Pipeline, Elastic Beanstalk, or EC2.  Do I need to do something special once I'm logged in to see what you created?  I wanted to get the public URL from Elastic Beanstalk so I could view the index page that you created.

**Comment by mrossi113** [comment]
@cruoti no you should be able to see it once you click on any of those services. So you should see a screen below when you go into the CodePipeline.
![screen shot 2017-06-15 at 11 00 35 am](https://user-images.githubusercontent.com/19477691/27187789-14cd86ac-51ba-11e7-9a7d-7cace293aa61.jpg)

@keeena are you able to see Pipeline, Elastic Beanstalk, and EC2 when you login to IAM?

If not I might I've missed a policy when creating the group. Everyone has the same permission in IAM except for the adding a policy to the group.

**Comment by ktaj** [comment]
@mrossi113 - I can access Elastic Beanstalk and EC2. However, I cannot access Pipeline. Error is as follows: "User: arn:aws:iam::213902690354:user/ktaj@brandeis.edu is not authorized to perform: datapipeline:GetAccountLimits (Service: DataPipeline; Status Code: 400; Error Code: AccessDeniedException; Request ID: 937c43ba-51e3-11e7-b154-0b3e632bf14d)"

**Comment by mrossi113** [comment]
@cruoti @ktaj I added administrator access policy to everyone user account. Which will give you access to all area even the IAM account. So you should be able to see everything. Could someone let me know if you have access to all areas that were discussed above?

@cruoti also here is the URL from Elastic Beanstalk app http://custom-env.pac9mpkmm6.us-east-1.elasticbeanstalk.com

**Comment by cruoti** [comment]
I still don't see anything.  Here's a screen shot looking at EC2.  You'll notice in the top right hand corner that it says I'm connected to the IAM account number.  Then in EC2 there is no running instances.  Looking at Elastic Beanstalk and CodePipeline it's the same.

![iam](https://user-images.githubusercontent.com/25518813/27208752-83458f16-5215-11e7-9d4b-876148c077df.PNG)

**Comment by mrossi113** [comment]
@cruoti okay I will look into this tonight.

**Comment by ktaj** [comment]
@mrossi113 I can access IAM and Pipeline with no issues. Just a check: there currently aren't any pipelines created, right? It sends me right to the "create" page.

**Comment by mrossi113** [comment]
@ktaj the pipeline has been created so I'm looking into now. The pipeline is called DiscApp.

**Comment by ktaj** [comment]
Interesting; I don't see the pipeline; just the "Get Started" screen. 

This is what I see on the IAM page:
![image](https://user-images.githubusercontent.com/29437411/27210638-c33010a4-5221-11e7-9776-1f6ff671cf92.png)

**Comment by mrossi113** [comment]
Change to N.Virginia to view any IAM services.
